### ISSUE TITLE
feat: github actions, 도커 기반 CI/CD 구축

### ISSUE THREAD

**Issue by doyeoo** [Team-DDingCon/DDingCon-Server#5]
### 📝 Description

---

github actions, 도커 기반 CI/CD 구축

### ✅ Tasks

---

- [ ] 도커허브 레포지토리 생성
- [ ] github actions deploy.yml 작성
- [ ] EC2 배포 스크립트 작성
- [ ] 배포 중 에러 발생 시 롤백
